#!/usr/bin/perl


# yesterday = time-86400  

$offset = 86400 * @ARGV[0];

@months = qw(Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec);
@weekDays = qw(Sun Mon Tue Wed Thu Fri Sat Sun);
($second, $minute, $hour, $dayOfMonth, $month, $yearOffset, $dayOfWeek, $dayOfYear, $daylightSavings) = localtime(time - $offset);
$year = 1900 + $yearOffset;
$theTime = "$hour:$minute:$second, $weekDays[$dayOfWeek] $months[$month] $dayOfMonth, $year";
$dayOfMonth=sprintf("%02d",$dayOfMonth);
$monthno=sprintf("%02d",$month+1);
printf "$year-$monthno-$dayOfMonth\n";

